#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x6013BD3AFCF957DE (daniele.varrazzo@gmail.com)
#
Name     : deprecated-setproctitle
Version  : 1.1.10
Release  : 21
URL      : http://pypi.debian.net/setproctitle/setproctitle-1.1.10.tar.gz
Source0  : http://pypi.debian.net/setproctitle/setproctitle-1.1.10.tar.gz
Source99 : http://pypi.debian.net/setproctitle/setproctitle-1.1.10.tar.gz.asc
Summary  : A Python module to customize the process title
Group    : Development/Tools
License  : BSD-3-Clause
Requires: deprecated-setproctitle-license = %{version}-%{release}
Requires: deprecated-setproctitle-python = %{version}-%{release}
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : python-dev

%description
A Python module to customize the process title
==============================================

%package legacypython
Summary: legacypython components for the deprecated-setproctitle package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-setproctitle package.


%package license
Summary: license components for the deprecated-setproctitle package.
Group: Default

%description license
license components for the deprecated-setproctitle package.


%package python
Summary: python components for the deprecated-setproctitle package.
Group: Default

%description python
python components for the deprecated-setproctitle package.


%prep
%setup -q -n setproctitle-1.1.10

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554328138
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecated-setproctitle
cp COPYRIGHT %{buildroot}/usr/share/package-licenses/deprecated-setproctitle/COPYRIGHT
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecated-setproctitle/COPYRIGHT

%files python
%defattr(-,root,root,-)
